### ISSUE TITLE
Init flows via helm ?

### ISSUE THREAD

**Issue by corentin59** [kestra-io/helm-charts#21]
### Feature description

Hello,

I am currently using Kestra via Kubernetes with Helm deployment. I would like to maintain a fairly stateless installation in the sense that my requirements are currently limited (meaning without storage). Is there a way during Helm deployment to create flows using the values.yaml file ?

Thx

**Comment by tchiotludo** [comment]
Not really sure to understand your use cases ? 
You still have the database and storage that will be stateful (even if you could delegate to others resource in the cloud) 
The flow definition are stored on that database and we advocate for using the [CI/CD to deploy](https://kestra.io/docs/developer-guide/cicd). 

We have some detail about stateless please.

**Comment by corentin59** [comment]
In fact, we currently see Kestra as a tooling component in our Kubernetes cluster, which is configured during the initialization of a new cluster. The lifespan of a Kubernetes cluster in our environment can be quite limited, ranging from a few days to a few months. With this in mind, it would be nice to have Kestra initialized on the fly with generic flows ready for use. Users can then add their own flows afterward. One could envision creating these generic flows as a sidekick or through API calls... However, if HELM supports it, it might be simpler for us at the moment ?

**Comment by tchiotludo** [comment]
We don't provide this in the helm charts but you could emulate this with a kubernetes job I think. 
You could: 
- mount a directory with the flow inside the job
- use the kestra image  
- use this command `./kestra flow namespace update --server http://<service-url> <your.namespace> <dir> --no-delete`
- Just start the command when you are sure the webserver is running 

Does this will work for you?

**Comment by corentin59** [comment]
THANKS,

That should do !

Corentin

**Comment by tchiotludo** [comment]
Closing since the solution seems ok for you, reopen if not
