### ISSUE TITLE
Update Postgres Version

### ISSUE THREAD

**Issue by ThierryGirod** [kestra-io/helm-charts#36]
### Feature description

I have an issue with deploying the your latest kestra chart (0.16.0)  to my ARM cluster.
![Screenshot from 2024-04-24 14-37-06](https://github.com/kestra-io/helm-charts/assets/10278762/e5f0ad46-42d5-4180-9346-f6f31c40fb53)

 This is because the postgres container used in your chart bitnami/postgresql:14.5.0-debian-11-r35 is not build for ARM.
See on dockerhub.
![Screenshot from 2024-04-24 14-38-54](https://github.com/kestra-io/helm-charts/assets/10278762/f5516aa5-7603-4a54-9fc9-cfe1f823c547)

Could you eventually update the chart to a version supporting complete ARM setup? That would be awesome.

Regards

**Comment by anna-geller** [comment]
Hi, this sounds like a great addition! Would you be willing to contribute a pull request?

**Comment by ThierryGirod** [comment]
Sure, any requirements from your side?
