### ISSUE TITLE
Expose Metric Service

### ISSUE THREAD

**Issue by kaliazur** [kestra-io/helm-charts#44]
### Feature description

Hi,
I want to export the metrics using an opentelemetry service in my k8s.
But the `kestra-standalone` deployment does not expose a service for the metric in `:8081/prometheus`
I found a workaround using the `kubectl expose deployment ...` to make that happen, but it's not really clean and difficult to automate.
Do you think you could implement a `service:` section in the `values.yaml` ( or something like that ) to create a service that achieve this purpose ?
Thank you

**Comment by loicmathieu** [comment]
We can conditionally expose the management endpoint in the service with a property disabled by default if it is needed.

**Comment by kaliazur** [comment]
Allright ! Do you mean that it's possible right now ? Like there is a way to do so ?
Or do you mean it could be a next feature ?
Thank you for your fast answer ! :muscle:

**Comment by loicmathieu** [comment]
Each pod has a port named `management` but this port is not available in the [service](https://github.com/kestra-io/helm-charts/blob/master/charts/kestra/templates/service.yaml).
We would need to implement a new feature to add this port to the service based on a property in the values file.

**Comment by kaliazur** [comment]
Thank you for your answer @loicmathieu ! :muscle: 
I wanted to make the modification, and create a PullRequest, but I cannot push in the repo due to a Permission Denied.
What is the process to contribute ?
Thank you again

**Comment by loicmathieu** [comment]
@kaliazur this would be great!

You need to fork the repo, create a branch in your own fork, and create a pull request.

**Comment by kaliazur** [comment]
Roger that @loicmathieu ! Thanks !
I created a Pull Request with those changes

**Comment by loicmathieu** [comment]
Done in https://github.com/kestra-io/helm-charts/pull/45
