### ISSUE TITLE
Allow passing extra resources in the chart

### ISSUE THREAD

**Issue by aqeelat** [kestra-io/helm-charts#46]
### Feature description

It would be really helpful if we can include additional resources in the chart so that they become associated with it and managed together as one helm release.

The current situation we're facing right now is that we have:
1. a SealedSecret object that contains our kestra config
2. the kestra release
However, the sealed secret is not associated with the release and therefore argocd cannot manage them as one unit.

**Comment by aqeelat** [comment]
This can be done by
* adding this to _helpers.tpl
```tpl
{{/*
Renders a value that contains template.
Usage:
{{ include "chart.render" ( dict "value" .Values.path.to.the.Value "context" $) }}
https://github.com/minio/operator/blob/v5.0.16/helm/tenant/templates/_helpers.tpl
*/}}
{{- define "chart.render" -}}
  {{- if typeIs "string" .value }}
    {{- tpl .value .context }}
  {{- else }}
    {{- tpl (.value | toYaml) .context }}
  {{- end }}
{{- end -}}
```
* creating a template file with
```yaml
{{- range .Values.extraResources }}
---
{{- include "chart.render" (dict "value" . "context" $) }}
{{- end }}
```
* adding `extraResources: []` anywhere in values.yaml

**Comment by hegerdes** [comment]
I created a PR for this in #49
