### ISSUE TITLE
Override default minio resources.requests.memory

### ISSUE THREAD

**Issue by dswiecki** [kestra-io/helm-charts#7]
### Issue description

For local k8s setups e.g. minikube, k3d override minio's defaults.
By default minio sets
[resources.requests.memory=16gb](https://github.com/minio/minio/blob/master/helm/minio/values.yaml#L260)
resulting in the helm install command waiting for resources
```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  10s   default-scheduler  0/2 nodes are available: 2 Insufficient memory.
```

As a workaround one can set this explicitly with
`helm install my-release kestra/kestra --set minio.resources.requests.memory=1Gi`

**Comment by tchiotludo** [comment]
@dswiecki: I think you could add this default request value on our helm charts, minio is not intended for production usage and people that care about need to tune the value I think
